# -*- coding: utf-8 -*-
"""타이타닉

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uxYUXwpSOefV9--eg-0Hju-ruhbrhM0p

### 3. Tackle the Titanic dataset
"""

from pathlib import Path
import pandas as pd
import tarfile
import urllib.request

def load_titanic_data():
    tarball_path = Path("datasets/titanic.tgz")
    if not tarball_path.is_file():
        Path("datasets").mkdir(parents=True, exist_ok=True)
        url = "https://github.com/ageron/data/raw/main/titanic.tgz"
        urllib.request.urlretrieve(url, tarball_path)
        with tarfile.open(tarball_path) as titanic_tarball:
            titanic_tarball.extractall(path="datasets")
    return [pd.read_csv(Path("datasets/titanic") / filename)
            for filename in ("train.csv", "test.csv")]

train_data, test_data = load_titanic_data()

"""데이터는 이미 학습 세트와 테스트 세트로 분할되어 있습니다. 그러나 테스트 데이터에는 레이블이 포함되어 있지 않습니다. 목표는 훈련 데이터를 사용하여 가능한 최고의 모델을 훈련한 다음 테스트 데이터에 대한 예측을 만들고 Kaggle에 업로드하여 최종 점수를 확인하는 것입니다 ."""

train_data.head()

"""PassengerId : 각 승객의 고유 식별자
Survived : 그것이 목표이며 0은 승객이 생존하지 못했음을 의미하고 1은 생존했음을 의미합니다.
Pclass : 여객 등급.
Name, Sex, Age : 자명
SibSp : 타이타닉에 탑승한 승객의 형제 및 배우자 수.
Parch : 타이타닉호에 탑승한 승객의 자녀와 부모의 수
Ticket : 티켓아이디
Fare : 지불한 가격(파운드)
Cabin : 승객의 캐빈 번호
Embarked : 승객이 타이타닉호에 승선한 곳

목표는 승객의 연령, 성별, 승객 등급, 승선 장소 등과 같은 속성을 기반으로 승객의 생존 여부를 예측하는 것입니다.

PassengerId열을 인덱스 열로 명시적으로 설정해 보겠습니다 .
"""

train_data = train_data.set_index("PassengerId")
test_data = test_data.set_index("PassengerId")

"""누락된 데이터의 양을 확인하기 위해 더 많은 정보를 얻겠습니다."""

train_data.info()

train_data[train_data["Sex"]=="female"]["Age"].median()

"""연령, 캐빈 및 선내 특성은 때때로 null(null이 아닌 891개 미만)이며, 특히 캐빈(77%가 null)입니다. 일단 캐빈은 무시하고 나머지는 집중하겠습니다. Age 속성의 null 값은 약 19%이므로 이 값으로 수행할 작업을 결정해야 합니다. null 값을 중위수 연령으로 대체하는 것이 합리적인 것 같습니다. 다른 열을 기준으로 나이를 예측하면 조금 더 현명해질 수 있습니다(예: 중위 연령은 1등 37세, 2등 29세, 3등 24세). 하지만 우리는 단순하게 유지하고 전체 중위 연령을 사용할 것입니다.

이름 및 티켓 특성 에는 약간의 값이 있을 수 있지만 모델이 사용할 수 있는 유용한 숫자로 변환하기가 약간 까다로울 수 있습니다. 따라서 지금은 무시하겠습니다.

숫자 속성을 살펴보겠습니다.
"""

train_data.describe()

"""38%만 살아남았습니다. 40%에 가깝기 때문에 정확도는 우리 모델을 평가하는 합리적인 척도가 될 것입니다.
평균 요금은 32.20파운드로 그다지 비싸지 않은 것 같습니다(당시에는 아마 많은 돈이었을 것입니다).
평균 연령은 30세 미만이었다.

대상이 실제로 0 또는 1인지 확인합시다.
"""

train_data["Survived"].value_counts()

train_data["Pclass"].value_counts()

train_data["Sex"].value_counts()

train_data["Embarked"].value_counts()

"""Embarked 속성은 승객이 승선한 위치를 알려줍니다. C=Cherbourg, Q=Queenstown, S=Southampton.

이제 숫자 속성에 대한 파이프라인부터 시작하여 전처리 파이프라인을 빌드해 보겠습니다.
"""

from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler

num_pipeline = Pipeline([
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler())
    ])

"""이제 범주 속성에 대한 파이프라인을 구축할 수 있습니다."""

from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder

cat_pipeline = Pipeline([
        ("ordinal_encoder", OrdinalEncoder()),    
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("cat_encoder", OneHotEncoder(sparse=False)),
    ])

"""마지막으로 수치 및 범주 파이프라인을 연결해 보겠습니다."""

from sklearn.compose import ColumnTransformer

num_attribs = ["Age", "SibSp", "Parch", "Fare"]
cat_attribs = ["Pclass", "Sex", "Embarked"]

preprocess_pipeline = ColumnTransformer([
        ("num", num_pipeline, num_attribs),
        ("cat", cat_pipeline, cat_attribs),
    ])

"""원시 데이터를 가져오고 우리가 원하는 기계 학습 모델에 공급할 수 있는 숫자 입력 기능을 출력하는 멋진 전처리 파이프라인을 가지고 있습니다."""

X_train = preprocess_pipeline.fit_transform(train_data)
X_train

y_train = train_data["Survived"]

from sklearn.ensemble import RandomForestClassifier
forest_clf = RandomForestClassifier(n_estimators=100, random_state=42)
forest_clf.fit(X_train, y_train)

"""모델이 훈련되었으니 이를 사용하여 테스트 세트에 대한 예측을 해봅시다."""

X_test = preprocess_pipeline.transform(test_data)
y_pred = forest_clf.predict(X_test)

from sklearn.model_selection import cross_val_score
forest_scores = cross_val_score(forest_clf, X_train, y_train, cv=10)
forest_scores.mean()

from sklearn.svm import SVC

svm_clf = SVC(gamma="auto")
svm_scores = cross_val_score(svm_clf, X_train, y_train, cv=10)
svm_scores.mean()

plt.figure(figsize=(8, 4))
plt.plot([1]*10, svm_scores, ".")
plt.plot([2]*10, forest_scores, ".")
plt.boxplot([svm_scores, forest_scores], labels=("SVM", "Random Forest"))
plt.ylabel("Accuracy")
plt.show()

"""랜덤 포레스트 분류기는 10개의 접기 중 하나에서 매우 높은 점수를 받았지만 전반적으로 평균 점수가 낮고 산포도가 더 커서 SVM 분류기가 더 잘 일반화될 가능성이 있는 것으로 보입니다.

이 결과를 더 개선하려면 다음을 수행할 수 있습니다.

교차 검증 및 그리드 검색을 사용하여 더 많은 모델을 비교하고 하이퍼파라미터를 조정합니다.
예를 들어 더 많은 기능 엔지니어링을 수행하십시오.
숫자 속성을 범주 속성으로 변환해 보십시오. 예를 들어, 연령 그룹마다 생존율이 매우 다르기 때문에(아래 참조) 연령 버킷 범주를 만들어 연령 대신 사용하는 것이 도움이 될 수 있습니다. 마찬가지로 혼자 여행하는 사람들 중 30%만이 살아남았기 때문에 혼자 여행하는 사람들을 위한 특별 범주가 있는 것이 유용할 수 있습니다(아래 참조).
SibSp 와 Parch를 합계로 바꿉니다 .
Survived 속성 과 잘 연관되는 이름 부분을 식별하십시오 .
예를 들어 Cabin 열을 사용하여 첫 글자를 범주 속성으로 처리합니다.
"""

train_data["AgeBucket"] = train_data["Age"] // 15 * 15
train_data[["AgeBucket", "Survived"]].groupby(['AgeBucket']).mean()

train_data["RelativesOnboard"] = train_data["SibSp"] + train_data["Parch"]
train_data[["RelativesOnboard", "Survived"]].groupby(
    ['RelativesOnboard']).mean()
